//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1318
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 2.0.50727.1318.
// 
using System;
using System.CodeDom.Compiler;
using System.ComponentModel;
using System.Diagnostics;
using System.Threading;
using System.Web.Services;
using System.Web.Services.Description;
using System.Web.Services.Protocols;
using System.Xml.Serialization;
using Xameleon.Properties;

#pragma warning disable 1591

namespace Xameleon.AmazonAWS.SQS {
    /// <remarks/>
    [GeneratedCode("System.Web.Services", "2.0.50727.1318")]
    [DebuggerStepThrough()]
    [DesignerCategory("code")]
    [WebServiceBinding(Name="QueueService", Namespace="http://queue.amazonaws.com/doc/2006-04-01/")]
    public partial class QueueService : SoapHttpClientProtocol {
        
        private SendOrPostCallback ListQueuesOperationCompleted;
        
        private SendOrPostCallback CreateQueueOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public QueueService() {
            this.Url = Settings.Default.Xameleon_AmazonAWS_SQS_QueueService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event ListQueuesCompletedEventHandler ListQueuesCompleted;
        
        /// <remarks/>
        public event CreateQueueCompletedEventHandler CreateQueueCompleted;
        
        /// <remarks/>
        [SoapDocumentMethod("ListQueues", Use=SoapBindingUse.Literal, ParameterStyle=SoapParameterStyle.Bare)]
        [return: XmlElement("ListQueuesResponse", Namespace="http://queue.amazonaws.com/doc/2006-04-01/")]
        public ListQueuesResponse ListQueues([XmlElement("ListQueues", Namespace="http://queue.amazonaws.com/doc/2006-04-01/")] ListQueues ListQueues1) {
            object[] results = this.Invoke("ListQueues", new object[] {
                        ListQueues1});
            return ((ListQueuesResponse)(results[0]));
        }
        
        /// <remarks/>
        public void ListQueuesAsync(ListQueues ListQueues1) {
            this.ListQueuesAsync(ListQueues1, null);
        }
        
        /// <remarks/>
        public void ListQueuesAsync(ListQueues ListQueues1, object userState) {
            if ((this.ListQueuesOperationCompleted == null)) {
                this.ListQueuesOperationCompleted = new SendOrPostCallback(this.OnListQueuesOperationCompleted);
            }
            this.InvokeAsync("ListQueues", new object[] {
                        ListQueues1}, this.ListQueuesOperationCompleted, userState);
        }
        
        private void OnListQueuesOperationCompleted(object arg) {
            if ((this.ListQueuesCompleted != null)) {
                InvokeCompletedEventArgs invokeArgs = ((InvokeCompletedEventArgs)(arg));
                this.ListQueuesCompleted(this, new ListQueuesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [SoapDocumentMethod("CreateQueue", Use=SoapBindingUse.Literal, ParameterStyle=SoapParameterStyle.Bare)]
        [return: XmlElement("CreateQueueResponse", Namespace="http://queue.amazonaws.com/doc/2006-04-01/")]
        public CreateQueueResponse CreateQueue([XmlElement("CreateQueue", Namespace="http://queue.amazonaws.com/doc/2006-04-01/")] CreateQueue CreateQueue1) {
            object[] results = this.Invoke("CreateQueue", new object[] {
                        CreateQueue1});
            return ((CreateQueueResponse)(results[0]));
        }
        
        /// <remarks/>
        public void CreateQueueAsync(CreateQueue CreateQueue1) {
            this.CreateQueueAsync(CreateQueue1, null);
        }
        
        /// <remarks/>
        public void CreateQueueAsync(CreateQueue CreateQueue1, object userState) {
            if ((this.CreateQueueOperationCompleted == null)) {
                this.CreateQueueOperationCompleted = new SendOrPostCallback(this.OnCreateQueueOperationCompleted);
            }
            this.InvokeAsync("CreateQueue", new object[] {
                        CreateQueue1}, this.CreateQueueOperationCompleted, userState);
        }
        
        private void OnCreateQueueOperationCompleted(object arg) {
            if ((this.CreateQueueCompleted != null)) {
                InvokeCompletedEventArgs invokeArgs = ((InvokeCompletedEventArgs)(arg));
                this.CreateQueueCompleted(this, new CreateQueueCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            Uri wsUri = new Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [GeneratedCode("System.Web.Services", "2.0.50727.1318")]
    [DebuggerStepThrough()]
    [DesignerCategory("code")]
    [WebServiceBinding(Name="MessageQueue", Namespace="http://queue.amazonaws.com/doc/2006-04-01/")]
    public partial class MessageQueue : SoapHttpClientProtocol {
        
        private SendOrPostCallback SendMessageOperationCompleted;
        
        private SendOrPostCallback ReceiveMessageOperationCompleted;
        
        private SendOrPostCallback PeekMessageOperationCompleted;
        
        private SendOrPostCallback DeleteMessageOperationCompleted;
        
        private SendOrPostCallback DeleteQueueOperationCompleted;
        
        private SendOrPostCallback SetVisibilityTimeoutOperationCompleted;
        
        private SendOrPostCallback GetVisibilityTimeoutOperationCompleted;
        
        private SendOrPostCallback AddGrantOperationCompleted;
        
        private SendOrPostCallback RemoveGrantOperationCompleted;
        
        private SendOrPostCallback ListGrantsOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public MessageQueue() {
            this.Url = Settings.Default.Xameleon_AmazonAWS_SQS_QueueService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event SendMessageCompletedEventHandler SendMessageCompleted;
        
        /// <remarks/>
        public event ReceiveMessageCompletedEventHandler ReceiveMessageCompleted;
        
        /// <remarks/>
        public event PeekMessageCompletedEventHandler PeekMessageCompleted;
        
        /// <remarks/>
        public event DeleteMessageCompletedEventHandler DeleteMessageCompleted;
        
        /// <remarks/>
        public event DeleteQueueCompletedEventHandler DeleteQueueCompleted;
        
        /// <remarks/>
        public event SetVisibilityTimeoutCompletedEventHandler SetVisibilityTimeoutCompleted;
        
        /// <remarks/>
        public event GetVisibilityTimeoutCompletedEventHandler GetVisibilityTimeoutCompleted;
        
        /// <remarks/>
        public event AddGrantCompletedEventHandler AddGrantCompleted;
        
        /// <remarks/>
        public event RemoveGrantCompletedEventHandler RemoveGrantCompleted;
        
        /// <remarks/>
        public event ListGrantsCompletedEventHandler ListGrantsCompleted;
        
        /// <remarks/>
        [SoapDocumentMethod("SendMessage", Use=SoapBindingUse.Literal, ParameterStyle=SoapParameterStyle.Bare)]
        [return: XmlElement("SendMessageResponse", Namespace="http://queue.amazonaws.com/doc/2006-04-01/")]
        public SendMessageResponse SendMessage([XmlElement("SendMessage", Namespace="http://queue.amazonaws.com/doc/2006-04-01/")] SendMessage SendMessage1) {
            object[] results = this.Invoke("SendMessage", new object[] {
                        SendMessage1});
            return ((SendMessageResponse)(results[0]));
        }
        
        /// <remarks/>
        public void SendMessageAsync(SendMessage SendMessage1) {
            this.SendMessageAsync(SendMessage1, null);
        }
        
        /// <remarks/>
        public void SendMessageAsync(SendMessage SendMessage1, object userState) {
            if ((this.SendMessageOperationCompleted == null)) {
                this.SendMessageOperationCompleted = new SendOrPostCallback(this.OnSendMessageOperationCompleted);
            }
            this.InvokeAsync("SendMessage", new object[] {
                        SendMessage1}, this.SendMessageOperationCompleted, userState);
        }
        
        private void OnSendMessageOperationCompleted(object arg) {
            if ((this.SendMessageCompleted != null)) {
                InvokeCompletedEventArgs invokeArgs = ((InvokeCompletedEventArgs)(arg));
                this.SendMessageCompleted(this, new SendMessageCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [SoapDocumentMethod("ReceiveMessage", Use=SoapBindingUse.Literal, ParameterStyle=SoapParameterStyle.Bare)]
        [return: XmlElement("ReceiveMessageResponse", Namespace="http://queue.amazonaws.com/doc/2006-04-01/")]
        public ReceiveMessageResponse ReceiveMessage([XmlElement("ReceiveMessage", Namespace="http://queue.amazonaws.com/doc/2006-04-01/")] ReceiveMessage ReceiveMessage1) {
            object[] results = this.Invoke("ReceiveMessage", new object[] {
                        ReceiveMessage1});
            return ((ReceiveMessageResponse)(results[0]));
        }
        
        /// <remarks/>
        public void ReceiveMessageAsync(ReceiveMessage ReceiveMessage1) {
            this.ReceiveMessageAsync(ReceiveMessage1, null);
        }
        
        /// <remarks/>
        public void ReceiveMessageAsync(ReceiveMessage ReceiveMessage1, object userState) {
            if ((this.ReceiveMessageOperationCompleted == null)) {
                this.ReceiveMessageOperationCompleted = new SendOrPostCallback(this.OnReceiveMessageOperationCompleted);
            }
            this.InvokeAsync("ReceiveMessage", new object[] {
                        ReceiveMessage1}, this.ReceiveMessageOperationCompleted, userState);
        }
        
        private void OnReceiveMessageOperationCompleted(object arg) {
            if ((this.ReceiveMessageCompleted != null)) {
                InvokeCompletedEventArgs invokeArgs = ((InvokeCompletedEventArgs)(arg));
                this.ReceiveMessageCompleted(this, new ReceiveMessageCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [SoapDocumentMethod("PeekMessage", Use=SoapBindingUse.Literal, ParameterStyle=SoapParameterStyle.Bare)]
        [return: XmlElement("PeekMessageResponse", Namespace="http://queue.amazonaws.com/doc/2006-04-01/")]
        public PeekMessageResponse PeekMessage([XmlElement("PeekMessage", Namespace="http://queue.amazonaws.com/doc/2006-04-01/")] PeekMessage PeekMessage1) {
            object[] results = this.Invoke("PeekMessage", new object[] {
                        PeekMessage1});
            return ((PeekMessageResponse)(results[0]));
        }
        
        /// <remarks/>
        public void PeekMessageAsync(PeekMessage PeekMessage1) {
            this.PeekMessageAsync(PeekMessage1, null);
        }
        
        /// <remarks/>
        public void PeekMessageAsync(PeekMessage PeekMessage1, object userState) {
            if ((this.PeekMessageOperationCompleted == null)) {
                this.PeekMessageOperationCompleted = new SendOrPostCallback(this.OnPeekMessageOperationCompleted);
            }
            this.InvokeAsync("PeekMessage", new object[] {
                        PeekMessage1}, this.PeekMessageOperationCompleted, userState);
        }
        
        private void OnPeekMessageOperationCompleted(object arg) {
            if ((this.PeekMessageCompleted != null)) {
                InvokeCompletedEventArgs invokeArgs = ((InvokeCompletedEventArgs)(arg));
                this.PeekMessageCompleted(this, new PeekMessageCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [SoapDocumentMethod("DeleteMessage", Use=SoapBindingUse.Literal, ParameterStyle=SoapParameterStyle.Bare)]
        [return: XmlElement("DeleteMessageResponse", Namespace="http://queue.amazonaws.com/doc/2006-04-01/")]
        public DeleteMessageResponse DeleteMessage([XmlElement("DeleteMessage", Namespace="http://queue.amazonaws.com/doc/2006-04-01/")] DeleteMessage DeleteMessage1) {
            object[] results = this.Invoke("DeleteMessage", new object[] {
                        DeleteMessage1});
            return ((DeleteMessageResponse)(results[0]));
        }
        
        /// <remarks/>
        public void DeleteMessageAsync(DeleteMessage DeleteMessage1) {
            this.DeleteMessageAsync(DeleteMessage1, null);
        }
        
        /// <remarks/>
        public void DeleteMessageAsync(DeleteMessage DeleteMessage1, object userState) {
            if ((this.DeleteMessageOperationCompleted == null)) {
                this.DeleteMessageOperationCompleted = new SendOrPostCallback(this.OnDeleteMessageOperationCompleted);
            }
            this.InvokeAsync("DeleteMessage", new object[] {
                        DeleteMessage1}, this.DeleteMessageOperationCompleted, userState);
        }
        
        private void OnDeleteMessageOperationCompleted(object arg) {
            if ((this.DeleteMessageCompleted != null)) {
                InvokeCompletedEventArgs invokeArgs = ((InvokeCompletedEventArgs)(arg));
                this.DeleteMessageCompleted(this, new DeleteMessageCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [SoapDocumentMethod("DeleteQueue", Use=SoapBindingUse.Literal, ParameterStyle=SoapParameterStyle.Bare)]
        [return: XmlElement("DeleteQueueResponse", Namespace="http://queue.amazonaws.com/doc/2006-04-01/")]
        public DeleteQueueResponse DeleteQueue([XmlElement("DeleteQueue", Namespace="http://queue.amazonaws.com/doc/2006-04-01/")] DeleteQueue DeleteQueue1) {
            object[] results = this.Invoke("DeleteQueue", new object[] {
                        DeleteQueue1});
            return ((DeleteQueueResponse)(results[0]));
        }
        
        /// <remarks/>
        public void DeleteQueueAsync(DeleteQueue DeleteQueue1) {
            this.DeleteQueueAsync(DeleteQueue1, null);
        }
        
        /// <remarks/>
        public void DeleteQueueAsync(DeleteQueue DeleteQueue1, object userState) {
            if ((this.DeleteQueueOperationCompleted == null)) {
                this.DeleteQueueOperationCompleted = new SendOrPostCallback(this.OnDeleteQueueOperationCompleted);
            }
            this.InvokeAsync("DeleteQueue", new object[] {
                        DeleteQueue1}, this.DeleteQueueOperationCompleted, userState);
        }
        
        private void OnDeleteQueueOperationCompleted(object arg) {
            if ((this.DeleteQueueCompleted != null)) {
                InvokeCompletedEventArgs invokeArgs = ((InvokeCompletedEventArgs)(arg));
                this.DeleteQueueCompleted(this, new DeleteQueueCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [SoapDocumentMethod("SetVisibilityTimeout", Use=SoapBindingUse.Literal, ParameterStyle=SoapParameterStyle.Bare)]
        [return: XmlElement("SetVisibilityTimeoutResponse", Namespace="http://queue.amazonaws.com/doc/2006-04-01/")]
        public SetVisibilityTimeoutResponse SetVisibilityTimeout([XmlElement("SetVisibilityTimeout", Namespace="http://queue.amazonaws.com/doc/2006-04-01/")] SetVisibilityTimeout SetVisibilityTimeout1) {
            object[] results = this.Invoke("SetVisibilityTimeout", new object[] {
                        SetVisibilityTimeout1});
            return ((SetVisibilityTimeoutResponse)(results[0]));
        }
        
        /// <remarks/>
        public void SetVisibilityTimeoutAsync(SetVisibilityTimeout SetVisibilityTimeout1) {
            this.SetVisibilityTimeoutAsync(SetVisibilityTimeout1, null);
        }
        
        /// <remarks/>
        public void SetVisibilityTimeoutAsync(SetVisibilityTimeout SetVisibilityTimeout1, object userState) {
            if ((this.SetVisibilityTimeoutOperationCompleted == null)) {
                this.SetVisibilityTimeoutOperationCompleted = new SendOrPostCallback(this.OnSetVisibilityTimeoutOperationCompleted);
            }
            this.InvokeAsync("SetVisibilityTimeout", new object[] {
                        SetVisibilityTimeout1}, this.SetVisibilityTimeoutOperationCompleted, userState);
        }
        
        private void OnSetVisibilityTimeoutOperationCompleted(object arg) {
            if ((this.SetVisibilityTimeoutCompleted != null)) {
                InvokeCompletedEventArgs invokeArgs = ((InvokeCompletedEventArgs)(arg));
                this.SetVisibilityTimeoutCompleted(this, new SetVisibilityTimeoutCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [SoapDocumentMethod("GetVisibilityTimeout", Use=SoapBindingUse.Literal, ParameterStyle=SoapParameterStyle.Bare)]
        [return: XmlElement("GetVisibilityTimeoutResponse", Namespace="http://queue.amazonaws.com/doc/2006-04-01/")]
        public GetVisibilityTimeoutResponse GetVisibilityTimeout([XmlElement("GetVisibilityTimeout", Namespace="http://queue.amazonaws.com/doc/2006-04-01/")] GetVisibilityTimeout GetVisibilityTimeout1) {
            object[] results = this.Invoke("GetVisibilityTimeout", new object[] {
                        GetVisibilityTimeout1});
            return ((GetVisibilityTimeoutResponse)(results[0]));
        }
        
        /// <remarks/>
        public void GetVisibilityTimeoutAsync(GetVisibilityTimeout GetVisibilityTimeout1) {
            this.GetVisibilityTimeoutAsync(GetVisibilityTimeout1, null);
        }
        
        /// <remarks/>
        public void GetVisibilityTimeoutAsync(GetVisibilityTimeout GetVisibilityTimeout1, object userState) {
            if ((this.GetVisibilityTimeoutOperationCompleted == null)) {
                this.GetVisibilityTimeoutOperationCompleted = new SendOrPostCallback(this.OnGetVisibilityTimeoutOperationCompleted);
            }
            this.InvokeAsync("GetVisibilityTimeout", new object[] {
                        GetVisibilityTimeout1}, this.GetVisibilityTimeoutOperationCompleted, userState);
        }
        
        private void OnGetVisibilityTimeoutOperationCompleted(object arg) {
            if ((this.GetVisibilityTimeoutCompleted != null)) {
                InvokeCompletedEventArgs invokeArgs = ((InvokeCompletedEventArgs)(arg));
                this.GetVisibilityTimeoutCompleted(this, new GetVisibilityTimeoutCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [SoapDocumentMethod("AddGrant", Use=SoapBindingUse.Literal, ParameterStyle=SoapParameterStyle.Bare)]
        [return: XmlElement("AddGrantResponse", Namespace="http://queue.amazonaws.com/doc/2006-04-01/")]
        public AddGrantResponse AddGrant([XmlElement("AddGrant", Namespace="http://queue.amazonaws.com/doc/2006-04-01/")] AddGrantRequest AddGrant1) {
            object[] results = this.Invoke("AddGrant", new object[] {
                        AddGrant1});
            return ((AddGrantResponse)(results[0]));
        }
        
        /// <remarks/>
        public void AddGrantAsync(AddGrantRequest AddGrant1) {
            this.AddGrantAsync(AddGrant1, null);
        }
        
        /// <remarks/>
        public void AddGrantAsync(AddGrantRequest AddGrant1, object userState) {
            if ((this.AddGrantOperationCompleted == null)) {
                this.AddGrantOperationCompleted = new SendOrPostCallback(this.OnAddGrantOperationCompleted);
            }
            this.InvokeAsync("AddGrant", new object[] {
                        AddGrant1}, this.AddGrantOperationCompleted, userState);
        }
        
        private void OnAddGrantOperationCompleted(object arg) {
            if ((this.AddGrantCompleted != null)) {
                InvokeCompletedEventArgs invokeArgs = ((InvokeCompletedEventArgs)(arg));
                this.AddGrantCompleted(this, new AddGrantCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [SoapDocumentMethod("RemoveGrant", Use=SoapBindingUse.Literal, ParameterStyle=SoapParameterStyle.Bare)]
        [return: XmlElement("RemoveGrantResponse", Namespace="http://queue.amazonaws.com/doc/2006-04-01/")]
        public RemoveGrantResponse RemoveGrant([XmlElement("RemoveGrant", Namespace="http://queue.amazonaws.com/doc/2006-04-01/")] RemoveGrantRequest RemoveGrant1) {
            object[] results = this.Invoke("RemoveGrant", new object[] {
                        RemoveGrant1});
            return ((RemoveGrantResponse)(results[0]));
        }
        
        /// <remarks/>
        public void RemoveGrantAsync(RemoveGrantRequest RemoveGrant1) {
            this.RemoveGrantAsync(RemoveGrant1, null);
        }
        
        /// <remarks/>
        public void RemoveGrantAsync(RemoveGrantRequest RemoveGrant1, object userState) {
            if ((this.RemoveGrantOperationCompleted == null)) {
                this.RemoveGrantOperationCompleted = new SendOrPostCallback(this.OnRemoveGrantOperationCompleted);
            }
            this.InvokeAsync("RemoveGrant", new object[] {
                        RemoveGrant1}, this.RemoveGrantOperationCompleted, userState);
        }
        
        private void OnRemoveGrantOperationCompleted(object arg) {
            if ((this.RemoveGrantCompleted != null)) {
                InvokeCompletedEventArgs invokeArgs = ((InvokeCompletedEventArgs)(arg));
                this.RemoveGrantCompleted(this, new RemoveGrantCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [SoapDocumentMethod("ListGrants", Use=SoapBindingUse.Literal, ParameterStyle=SoapParameterStyle.Bare)]
        [return: XmlElement("ListGrantsResponse", Namespace="http://queue.amazonaws.com/doc/2006-04-01/")]
        public ListGrantsResponse ListGrants([XmlElement("ListGrants", Namespace="http://queue.amazonaws.com/doc/2006-04-01/")] ListGrantsRequest ListGrants1) {
            object[] results = this.Invoke("ListGrants", new object[] {
                        ListGrants1});
            return ((ListGrantsResponse)(results[0]));
        }
        
        /// <remarks/>
        public void ListGrantsAsync(ListGrantsRequest ListGrants1) {
            this.ListGrantsAsync(ListGrants1, null);
        }
        
        /// <remarks/>
        public void ListGrantsAsync(ListGrantsRequest ListGrants1, object userState) {
            if ((this.ListGrantsOperationCompleted == null)) {
                this.ListGrantsOperationCompleted = new SendOrPostCallback(this.OnListGrantsOperationCompleted);
            }
            this.InvokeAsync("ListGrants", new object[] {
                        ListGrants1}, this.ListGrantsOperationCompleted, userState);
        }
        
        private void OnListGrantsOperationCompleted(object arg) {
            if ((this.ListGrantsCompleted != null)) {
                InvokeCompletedEventArgs invokeArgs = ((InvokeCompletedEventArgs)(arg));
                this.ListGrantsCompleted(this, new ListGrantsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            Uri wsUri = new Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [GeneratedCode("System.Xml", "2.0.50727.1318")]
    [Serializable()]
    [DebuggerStepThrough()]
    [DesignerCategory("code")]
    [XmlType(AnonymousType=true, Namespace="http://queue.amazonaws.com/doc/2006-04-01/")]
    public partial class ListQueues {
        
        private string queueNamePrefixField;
        
        /// <remarks/>
        [XmlElement(DataType="NCName")]
        public string QueueNamePrefix {
            get {
                return this.queueNamePrefixField;
            }
            set {
                this.queueNamePrefixField = value;
            }
        }
    }
    
    /// <remarks/>
    [GeneratedCode("System.Xml", "2.0.50727.1318")]
    [Serializable()]
    [DebuggerStepThrough()]
    [DesignerCategory("code")]
    [XmlType(Namespace="http://access.amazonaws.com/doc/2006-01-01/")]
    public partial class Grant {
        
        private Grantee granteeField;
        
        private string permissionField;
        
        /// <remarks/>
        public Grantee Grantee {
            get {
                return this.granteeField;
            }
            set {
                this.granteeField = value;
            }
        }
        
        /// <remarks/>
        public string Permission {
            get {
                return this.permissionField;
            }
            set {
                this.permissionField = value;
            }
        }
    }
    
    /// <remarks/>
    [XmlInclude(typeof(Group))]
    [XmlInclude(typeof(User))]
    [XmlInclude(typeof(CanonicalUser))]
    [XmlInclude(typeof(AmazonCredential))]
    [XmlInclude(typeof(AmazonCustomerByEmail))]
    [GeneratedCode("System.Xml", "2.0.50727.1318")]
    [Serializable()]
    [DebuggerStepThrough()]
    [DesignerCategory("code")]
    [XmlType(Namespace="http://access.amazonaws.com/doc/2006-01-01/")]
    public abstract partial class Grantee {
    }
    
    /// <remarks/>
    [GeneratedCode("System.Xml", "2.0.50727.1318")]
    [Serializable()]
    [DebuggerStepThrough()]
    [DesignerCategory("code")]
    [XmlType(Namespace="http://access.amazonaws.com/doc/2006-01-01/")]
    public partial class Group : Grantee {
        
        private string uRIField;
        
        /// <remarks/>
        [XmlElement(DataType="anyURI")]
        public string URI {
            get {
                return this.uRIField;
            }
            set {
                this.uRIField = value;
            }
        }
    }
    
    /// <remarks/>
    [XmlInclude(typeof(CanonicalUser))]
    [XmlInclude(typeof(AmazonCredential))]
    [XmlInclude(typeof(AmazonCustomerByEmail))]
    [GeneratedCode("System.Xml", "2.0.50727.1318")]
    [Serializable()]
    [DebuggerStepThrough()]
    [DesignerCategory("code")]
    [XmlType(Namespace="http://access.amazonaws.com/doc/2006-01-01/")]
    public abstract partial class User : Grantee {
    }
    
    /// <remarks/>
    [GeneratedCode("System.Xml", "2.0.50727.1318")]
    [Serializable()]
    [DebuggerStepThrough()]
    [DesignerCategory("code")]
    [XmlType(Namespace="http://access.amazonaws.com/doc/2006-01-01/")]
    public partial class CanonicalUser : User {
        
        private string idField;
        
        private string displayNameField;
        
        /// <remarks/>
        public string ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string DisplayName {
            get {
                return this.displayNameField;
            }
            set {
                this.displayNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [GeneratedCode("System.Xml", "2.0.50727.1318")]
    [Serializable()]
    [DebuggerStepThrough()]
    [DesignerCategory("code")]
    [XmlType(Namespace="http://access.amazonaws.com/doc/2006-01-01/")]
    public partial class AmazonCredential : User {
        
        private string credentialField;
        
        /// <remarks/>
        public string Credential {
            get {
                return this.credentialField;
            }
            set {
                this.credentialField = value;
            }
        }
    }
    
    /// <remarks/>
    [GeneratedCode("System.Xml", "2.0.50727.1318")]
    [Serializable()]
    [DebuggerStepThrough()]
    [DesignerCategory("code")]
    [XmlType(Namespace="http://access.amazonaws.com/doc/2006-01-01/")]
    public partial class AmazonCustomerByEmail : User {
        
        private string emailAddressField;
        
        /// <remarks/>
        public string EmailAddress {
            get {
                return this.emailAddressField;
            }
            set {
                this.emailAddressField = value;
            }
        }
    }
    
    /// <remarks/>
    [GeneratedCode("System.Xml", "2.0.50727.1318")]
    [Serializable()]
    [DebuggerStepThrough()]
    [DesignerCategory("code")]
    [XmlType(Namespace="http://access.amazonaws.com/doc/2006-01-01/")]
    public partial class ListGrantsResponse {
        
        private Grant[] grantListField;
        
        private ResponseStatus1 responseStatusField;
        
        /// <remarks/>
        [XmlElement("GrantList")]
        public Grant[] GrantList {
            get {
                return this.grantListField;
            }
            set {
                this.grantListField = value;
            }
        }
        
        /// <remarks/>
        public ResponseStatus1 ResponseStatus {
            get {
                return this.responseStatusField;
            }
            set {
                this.responseStatusField = value;
            }
        }
    }
    
    /// <remarks/>
    [GeneratedCode("System.Xml", "2.0.50727.1318")]
    [Serializable()]
    [DebuggerStepThrough()]
    [DesignerCategory("code")]
    [XmlType(TypeName="ResponseStatus", Namespace="http://access.amazonaws.com/doc/2006-01-01/")]
    public partial class ResponseStatus1 {
        
        private string statusCodeField;
        
        private string statusMessageField;
        
        /// <remarks/>
        public string StatusCode {
            get {
                return this.statusCodeField;
            }
            set {
                this.statusCodeField = value;
            }
        }
        
        /// <remarks/>
        public string StatusMessage {
            get {
                return this.statusMessageField;
            }
            set {
                this.statusMessageField = value;
            }
        }
    }
    
    /// <remarks/>
    [GeneratedCode("System.Xml", "2.0.50727.1318")]
    [Serializable()]
    [DebuggerStepThrough()]
    [DesignerCategory("code")]
    [XmlType(Namespace="http://access.amazonaws.com/doc/2006-01-01/")]
    public partial class ListGrantsRequest {
        
        private Grantee granteeField;
        
        private string permissionField;
        
        /// <remarks/>
        public Grantee Grantee {
            get {
                return this.granteeField;
            }
            set {
                this.granteeField = value;
            }
        }
        
        /// <remarks/>
        public string Permission {
            get {
                return this.permissionField;
            }
            set {
                this.permissionField = value;
            }
        }
    }
    
    /// <remarks/>
    [GeneratedCode("System.Xml", "2.0.50727.1318")]
    [Serializable()]
    [DebuggerStepThrough()]
    [DesignerCategory("code")]
    [XmlType(Namespace="http://access.amazonaws.com/doc/2006-01-01/")]
    public partial class RemoveGrantResponse {
        
        private ResponseStatus1 responseStatusField;
        
        /// <remarks/>
        public ResponseStatus1 ResponseStatus {
            get {
                return this.responseStatusField;
            }
            set {
                this.responseStatusField = value;
            }
        }
    }
    
    /// <remarks/>
    [GeneratedCode("System.Xml", "2.0.50727.1318")]
    [Serializable()]
    [DebuggerStepThrough()]
    [DesignerCategory("code")]
    [XmlType(Namespace="http://access.amazonaws.com/doc/2006-01-01/")]
    public partial class RemoveGrantRequest {
        
        private Grantee granteeField;
        
        private string permissionField;
        
        /// <remarks/>
        public Grantee Grantee {
            get {
                return this.granteeField;
            }
            set {
                this.granteeField = value;
            }
        }
        
        /// <remarks/>
        public string Permission {
            get {
                return this.permissionField;
            }
            set {
                this.permissionField = value;
            }
        }
    }
    
    /// <remarks/>
    [GeneratedCode("System.Xml", "2.0.50727.1318")]
    [Serializable()]
    [DebuggerStepThrough()]
    [DesignerCategory("code")]
    [XmlType(Namespace="http://access.amazonaws.com/doc/2006-01-01/")]
    public partial class AddGrantResponse {
        
        private ResponseStatus1 responseStatusField;
        
        /// <remarks/>
        public ResponseStatus1 ResponseStatus {
            get {
                return this.responseStatusField;
            }
            set {
                this.responseStatusField = value;
            }
        }
    }
    
    /// <remarks/>
    [GeneratedCode("System.Xml", "2.0.50727.1318")]
    [Serializable()]
    [DebuggerStepThrough()]
    [DesignerCategory("code")]
    [XmlType(Namespace="http://access.amazonaws.com/doc/2006-01-01/")]
    public partial class AddGrantRequest {
        
        private Grantee granteeField;
        
        private string permissionField;
        
        /// <remarks/>
        public Grantee Grantee {
            get {
                return this.granteeField;
            }
            set {
                this.granteeField = value;
            }
        }
        
        /// <remarks/>
        public string Permission {
            get {
                return this.permissionField;
            }
            set {
                this.permissionField = value;
            }
        }
    }
    
    /// <remarks/>
    [GeneratedCode("System.Xml", "2.0.50727.1318")]
    [Serializable()]
    [DebuggerStepThrough()]
    [DesignerCategory("code")]
    [XmlType(AnonymousType=true, Namespace="http://queue.amazonaws.com/doc/2006-04-01/")]
    public partial class ListQueuesResponse {
        
        private string[] queueUrlField;
        
        private ResponseStatus responseStatusField;
        
        /// <remarks/>
        [XmlElement("QueueUrl", DataType="anyURI")]
        public string[] QueueUrl {
            get {
                return this.queueUrlField;
            }
            set {
                this.queueUrlField = value;
            }
        }
        
        /// <remarks/>
        public ResponseStatus ResponseStatus {
            get {
                return this.responseStatusField;
            }
            set {
                this.responseStatusField = value;
            }
        }
    }
    
    /// <remarks/>
    [GeneratedCode("System.Xml", "2.0.50727.1318")]
    [Serializable()]
    [DebuggerStepThrough()]
    [DesignerCategory("code")]
    [XmlType(AnonymousType=true, Namespace="http://queue.amazonaws.com/doc/2006-04-01/")]
    public partial class ResponseStatus {
        
        private string statusCodeField;
        
        private string messageField;
        
        private string requestIdField;
        
        /// <remarks/>
        public string StatusCode {
            get {
                return this.statusCodeField;
            }
            set {
                this.statusCodeField = value;
            }
        }
        
        /// <remarks/>
        public string Message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
            }
        }
        
        /// <remarks/>
        public string RequestId {
            get {
                return this.requestIdField;
            }
            set {
                this.requestIdField = value;
            }
        }
    }
    
    /// <remarks/>
    [GeneratedCode("System.Xml", "2.0.50727.1318")]
    [Serializable()]
    [DebuggerStepThrough()]
    [DesignerCategory("code")]
    [XmlType(AnonymousType=true, Namespace="http://queue.amazonaws.com/doc/2006-04-01/")]
    public partial class CreateQueue {
        
        private string queueNameField;
        
        private string defaultVisibilityTimeoutField;
        
        /// <remarks/>
        [XmlElement(DataType="NCName")]
        public string QueueName {
            get {
                return this.queueNameField;
            }
            set {
                this.queueNameField = value;
            }
        }
        
        /// <remarks/>
        [XmlElement(DataType="integer")]
        public string DefaultVisibilityTimeout {
            get {
                return this.defaultVisibilityTimeoutField;
            }
            set {
                this.defaultVisibilityTimeoutField = value;
            }
        }
    }
    
    /// <remarks/>
    [GeneratedCode("System.Xml", "2.0.50727.1318")]
    [Serializable()]
    [DebuggerStepThrough()]
    [DesignerCategory("code")]
    [XmlType(AnonymousType=true, Namespace="http://queue.amazonaws.com/doc/2006-04-01/")]
    public partial class CreateQueueResponse {
        
        private string queueUrlField;
        
        private ResponseStatus responseStatusField;
        
        /// <remarks/>
        [XmlElement(DataType="anyURI")]
        public string QueueUrl {
            get {
                return this.queueUrlField;
            }
            set {
                this.queueUrlField = value;
            }
        }
        
        /// <remarks/>
        public ResponseStatus ResponseStatus {
            get {
                return this.responseStatusField;
            }
            set {
                this.responseStatusField = value;
            }
        }
    }
    
    /// <remarks/>
    [GeneratedCode("System.Xml", "2.0.50727.1318")]
    [Serializable()]
    [DebuggerStepThrough()]
    [DesignerCategory("code")]
    [XmlType(AnonymousType=true, Namespace="http://queue.amazonaws.com/doc/2006-04-01/")]
    public partial class SendMessage {
        
        private string messageBodyField;
        
        /// <remarks/>
        public string MessageBody {
            get {
                return this.messageBodyField;
            }
            set {
                this.messageBodyField = value;
            }
        }
    }
    
    /// <remarks/>
    [GeneratedCode("System.Xml", "2.0.50727.1318")]
    [Serializable()]
    [DebuggerStepThrough()]
    [DesignerCategory("code")]
    [XmlType(AnonymousType=true, Namespace="http://queue.amazonaws.com/doc/2006-04-01/")]
    public partial class SendMessageResponse {
        
        private string messageIdField;
        
        private ResponseStatus responseStatusField;
        
        /// <remarks/>
        public string MessageId {
            get {
                return this.messageIdField;
            }
            set {
                this.messageIdField = value;
            }
        }
        
        /// <remarks/>
        public ResponseStatus ResponseStatus {
            get {
                return this.responseStatusField;
            }
            set {
                this.responseStatusField = value;
            }
        }
    }
    
    /// <remarks/>
    [GeneratedCode("System.Xml", "2.0.50727.1318")]
    [Serializable()]
    [DebuggerStepThrough()]
    [DesignerCategory("code")]
    [XmlType(AnonymousType=true, Namespace="http://queue.amazonaws.com/doc/2006-04-01/")]
    public partial class ReceiveMessage {
        
        private string numberOfMessagesField;
        
        private string visibilityTimeoutField;
        
        /// <remarks/>
        [XmlElement(DataType="integer")]
        public string NumberOfMessages {
            get {
                return this.numberOfMessagesField;
            }
            set {
                this.numberOfMessagesField = value;
            }
        }
        
        /// <remarks/>
        [XmlElement(DataType="integer")]
        public string VisibilityTimeout {
            get {
                return this.visibilityTimeoutField;
            }
            set {
                this.visibilityTimeoutField = value;
            }
        }
    }
    
    /// <remarks/>
    [GeneratedCode("System.Xml", "2.0.50727.1318")]
    [Serializable()]
    [DebuggerStepThrough()]
    [DesignerCategory("code")]
    [XmlType(AnonymousType=true, Namespace="http://queue.amazonaws.com/doc/2006-04-01/")]
    public partial class ReceiveMessageResponse {
        
        private Message[] messageField;
        
        private ResponseStatus responseStatusField;
        
        /// <remarks/>
        [XmlElement("Message")]
        public Message[] Message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
            }
        }
        
        /// <remarks/>
        public ResponseStatus ResponseStatus {
            get {
                return this.responseStatusField;
            }
            set {
                this.responseStatusField = value;
            }
        }
    }
    
    /// <remarks/>
    [GeneratedCode("System.Xml", "2.0.50727.1318")]
    [Serializable()]
    [DebuggerStepThrough()]
    [DesignerCategory("code")]
    [XmlType(AnonymousType=true, Namespace="http://queue.amazonaws.com/doc/2006-04-01/")]
    public partial class Message {
        
        private string messageIdField;
        
        private string messageBodyField;
        
        /// <remarks/>
        public string MessageId {
            get {
                return this.messageIdField;
            }
            set {
                this.messageIdField = value;
            }
        }
        
        /// <remarks/>
        public string MessageBody {
            get {
                return this.messageBodyField;
            }
            set {
                this.messageBodyField = value;
            }
        }
    }
    
    /// <remarks/>
    [GeneratedCode("System.Xml", "2.0.50727.1318")]
    [Serializable()]
    [DebuggerStepThrough()]
    [DesignerCategory("code")]
    [XmlType(AnonymousType=true, Namespace="http://queue.amazonaws.com/doc/2006-04-01/")]
    public partial class PeekMessage {
        
        private string messageIdField;
        
        /// <remarks/>
        public string MessageId {
            get {
                return this.messageIdField;
            }
            set {
                this.messageIdField = value;
            }
        }
    }
    
    /// <remarks/>
    [GeneratedCode("System.Xml", "2.0.50727.1318")]
    [Serializable()]
    [DebuggerStepThrough()]
    [DesignerCategory("code")]
    [XmlType(AnonymousType=true, Namespace="http://queue.amazonaws.com/doc/2006-04-01/")]
    public partial class PeekMessageResponse {
        
        private Message messageField;
        
        private ResponseStatus responseStatusField;
        
        /// <remarks/>
        public Message Message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
            }
        }
        
        /// <remarks/>
        public ResponseStatus ResponseStatus {
            get {
                return this.responseStatusField;
            }
            set {
                this.responseStatusField = value;
            }
        }
    }
    
    /// <remarks/>
    [GeneratedCode("System.Xml", "2.0.50727.1318")]
    [Serializable()]
    [DebuggerStepThrough()]
    [DesignerCategory("code")]
    [XmlType(AnonymousType=true, Namespace="http://queue.amazonaws.com/doc/2006-04-01/")]
    public partial class DeleteMessage {
        
        private string messageIdField;
        
        /// <remarks/>
        public string MessageId {
            get {
                return this.messageIdField;
            }
            set {
                this.messageIdField = value;
            }
        }
    }
    
    /// <remarks/>
    [GeneratedCode("System.Xml", "2.0.50727.1318")]
    [Serializable()]
    [DebuggerStepThrough()]
    [DesignerCategory("code")]
    [XmlType(AnonymousType=true, Namespace="http://queue.amazonaws.com/doc/2006-04-01/")]
    public partial class DeleteMessageResponse {
        
        private ResponseStatus responseStatusField;
        
        /// <remarks/>
        public ResponseStatus ResponseStatus {
            get {
                return this.responseStatusField;
            }
            set {
                this.responseStatusField = value;
            }
        }
    }
    
    /// <remarks/>
    [GeneratedCode("System.Xml", "2.0.50727.1318")]
    [Serializable()]
    [DebuggerStepThrough()]
    [DesignerCategory("code")]
    [XmlType(AnonymousType=true, Namespace="http://queue.amazonaws.com/doc/2006-04-01/")]
    public partial class DeleteQueue {
    }
    
    /// <remarks/>
    [GeneratedCode("System.Xml", "2.0.50727.1318")]
    [Serializable()]
    [DebuggerStepThrough()]
    [DesignerCategory("code")]
    [XmlType(AnonymousType=true, Namespace="http://queue.amazonaws.com/doc/2006-04-01/")]
    public partial class DeleteQueueResponse {
        
        private ResponseStatus responseStatusField;
        
        /// <remarks/>
        public ResponseStatus ResponseStatus {
            get {
                return this.responseStatusField;
            }
            set {
                this.responseStatusField = value;
            }
        }
    }
    
    /// <remarks/>
    [GeneratedCode("System.Xml", "2.0.50727.1318")]
    [Serializable()]
    [DebuggerStepThrough()]
    [DesignerCategory("code")]
    [XmlType(AnonymousType=true, Namespace="http://queue.amazonaws.com/doc/2006-04-01/")]
    public partial class SetVisibilityTimeout {
        
        private string visibilityTimeoutField;
        
        /// <remarks/>
        [XmlElement(DataType="integer")]
        public string VisibilityTimeout {
            get {
                return this.visibilityTimeoutField;
            }
            set {
                this.visibilityTimeoutField = value;
            }
        }
    }
    
    /// <remarks/>
    [GeneratedCode("System.Xml", "2.0.50727.1318")]
    [Serializable()]
    [DebuggerStepThrough()]
    [DesignerCategory("code")]
    [XmlType(AnonymousType=true, Namespace="http://queue.amazonaws.com/doc/2006-04-01/")]
    public partial class SetVisibilityTimeoutResponse {
        
        private ResponseStatus responseStatusField;
        
        /// <remarks/>
        public ResponseStatus ResponseStatus {
            get {
                return this.responseStatusField;
            }
            set {
                this.responseStatusField = value;
            }
        }
    }
    
    /// <remarks/>
    [GeneratedCode("System.Xml", "2.0.50727.1318")]
    [Serializable()]
    [DebuggerStepThrough()]
    [DesignerCategory("code")]
    [XmlType(AnonymousType=true, Namespace="http://queue.amazonaws.com/doc/2006-04-01/")]
    public partial class GetVisibilityTimeout {
    }
    
    /// <remarks/>
    [GeneratedCode("System.Xml", "2.0.50727.1318")]
    [Serializable()]
    [DebuggerStepThrough()]
    [DesignerCategory("code")]
    [XmlType(AnonymousType=true, Namespace="http://queue.amazonaws.com/doc/2006-04-01/")]
    public partial class GetVisibilityTimeoutResponse {
        
        private string visibilityTimeoutField;
        
        private ResponseStatus responseStatusField;
        
        /// <remarks/>
        [XmlElement(DataType="integer")]
        public string VisibilityTimeout {
            get {
                return this.visibilityTimeoutField;
            }
            set {
                this.visibilityTimeoutField = value;
            }
        }
        
        /// <remarks/>
        public ResponseStatus ResponseStatus {
            get {
                return this.responseStatusField;
            }
            set {
                this.responseStatusField = value;
            }
        }
    }
    
    /// <remarks/>
    [GeneratedCode("System.Web.Services", "2.0.50727.1318")]
    public delegate void ListQueuesCompletedEventHandler(object sender, ListQueuesCompletedEventArgs e);
    
    /// <remarks/>
    [GeneratedCode("System.Web.Services", "2.0.50727.1318")]
    [DebuggerStepThrough()]
    [DesignerCategory("code")]
    public partial class ListQueuesCompletedEventArgs : AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ListQueuesCompletedEventArgs(object[] results, Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ListQueuesResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ListQueuesResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [GeneratedCode("System.Web.Services", "2.0.50727.1318")]
    public delegate void CreateQueueCompletedEventHandler(object sender, CreateQueueCompletedEventArgs e);
    
    /// <remarks/>
    [GeneratedCode("System.Web.Services", "2.0.50727.1318")]
    [DebuggerStepThrough()]
    [DesignerCategory("code")]
    public partial class CreateQueueCompletedEventArgs : AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CreateQueueCompletedEventArgs(object[] results, Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public CreateQueueResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((CreateQueueResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [GeneratedCode("System.Web.Services", "2.0.50727.1318")]
    public delegate void SendMessageCompletedEventHandler(object sender, SendMessageCompletedEventArgs e);
    
    /// <remarks/>
    [GeneratedCode("System.Web.Services", "2.0.50727.1318")]
    [DebuggerStepThrough()]
    [DesignerCategory("code")]
    public partial class SendMessageCompletedEventArgs : AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SendMessageCompletedEventArgs(object[] results, Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public SendMessageResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((SendMessageResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [GeneratedCode("System.Web.Services", "2.0.50727.1318")]
    public delegate void ReceiveMessageCompletedEventHandler(object sender, ReceiveMessageCompletedEventArgs e);
    
    /// <remarks/>
    [GeneratedCode("System.Web.Services", "2.0.50727.1318")]
    [DebuggerStepThrough()]
    [DesignerCategory("code")]
    public partial class ReceiveMessageCompletedEventArgs : AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ReceiveMessageCompletedEventArgs(object[] results, Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ReceiveMessageResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ReceiveMessageResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [GeneratedCode("System.Web.Services", "2.0.50727.1318")]
    public delegate void PeekMessageCompletedEventHandler(object sender, PeekMessageCompletedEventArgs e);
    
    /// <remarks/>
    [GeneratedCode("System.Web.Services", "2.0.50727.1318")]
    [DebuggerStepThrough()]
    [DesignerCategory("code")]
    public partial class PeekMessageCompletedEventArgs : AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal PeekMessageCompletedEventArgs(object[] results, Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public PeekMessageResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((PeekMessageResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [GeneratedCode("System.Web.Services", "2.0.50727.1318")]
    public delegate void DeleteMessageCompletedEventHandler(object sender, DeleteMessageCompletedEventArgs e);
    
    /// <remarks/>
    [GeneratedCode("System.Web.Services", "2.0.50727.1318")]
    [DebuggerStepThrough()]
    [DesignerCategory("code")]
    public partial class DeleteMessageCompletedEventArgs : AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal DeleteMessageCompletedEventArgs(object[] results, Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public DeleteMessageResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((DeleteMessageResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [GeneratedCode("System.Web.Services", "2.0.50727.1318")]
    public delegate void DeleteQueueCompletedEventHandler(object sender, DeleteQueueCompletedEventArgs e);
    
    /// <remarks/>
    [GeneratedCode("System.Web.Services", "2.0.50727.1318")]
    [DebuggerStepThrough()]
    [DesignerCategory("code")]
    public partial class DeleteQueueCompletedEventArgs : AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal DeleteQueueCompletedEventArgs(object[] results, Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public DeleteQueueResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((DeleteQueueResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [GeneratedCode("System.Web.Services", "2.0.50727.1318")]
    public delegate void SetVisibilityTimeoutCompletedEventHandler(object sender, SetVisibilityTimeoutCompletedEventArgs e);
    
    /// <remarks/>
    [GeneratedCode("System.Web.Services", "2.0.50727.1318")]
    [DebuggerStepThrough()]
    [DesignerCategory("code")]
    public partial class SetVisibilityTimeoutCompletedEventArgs : AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SetVisibilityTimeoutCompletedEventArgs(object[] results, Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public SetVisibilityTimeoutResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((SetVisibilityTimeoutResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [GeneratedCode("System.Web.Services", "2.0.50727.1318")]
    public delegate void GetVisibilityTimeoutCompletedEventHandler(object sender, GetVisibilityTimeoutCompletedEventArgs e);
    
    /// <remarks/>
    [GeneratedCode("System.Web.Services", "2.0.50727.1318")]
    [DebuggerStepThrough()]
    [DesignerCategory("code")]
    public partial class GetVisibilityTimeoutCompletedEventArgs : AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetVisibilityTimeoutCompletedEventArgs(object[] results, Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public GetVisibilityTimeoutResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((GetVisibilityTimeoutResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [GeneratedCode("System.Web.Services", "2.0.50727.1318")]
    public delegate void AddGrantCompletedEventHandler(object sender, AddGrantCompletedEventArgs e);
    
    /// <remarks/>
    [GeneratedCode("System.Web.Services", "2.0.50727.1318")]
    [DebuggerStepThrough()]
    [DesignerCategory("code")]
    public partial class AddGrantCompletedEventArgs : AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AddGrantCompletedEventArgs(object[] results, Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public AddGrantResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((AddGrantResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [GeneratedCode("System.Web.Services", "2.0.50727.1318")]
    public delegate void RemoveGrantCompletedEventHandler(object sender, RemoveGrantCompletedEventArgs e);
    
    /// <remarks/>
    [GeneratedCode("System.Web.Services", "2.0.50727.1318")]
    [DebuggerStepThrough()]
    [DesignerCategory("code")]
    public partial class RemoveGrantCompletedEventArgs : AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal RemoveGrantCompletedEventArgs(object[] results, Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public RemoveGrantResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((RemoveGrantResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [GeneratedCode("System.Web.Services", "2.0.50727.1318")]
    public delegate void ListGrantsCompletedEventHandler(object sender, ListGrantsCompletedEventArgs e);
    
    /// <remarks/>
    [GeneratedCode("System.Web.Services", "2.0.50727.1318")]
    [DebuggerStepThrough()]
    [DesignerCategory("code")]
    public partial class ListGrantsCompletedEventArgs : AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ListGrantsCompletedEventArgs(object[] results, Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ListGrantsResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ListGrantsResponse)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591