//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 2.0.50727.42.
// 
#pragma warning disable 1591

namespace Xameleon.AmazonAWS.SQS {
    using System.Diagnostics;
    using System.Web.Services;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="QueueService", Namespace="http://queue.amazonaws.com/doc/2006-04-01/")]
    public partial class QueueService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback ListQueuesOperationCompleted;
        
        private System.Threading.SendOrPostCallback CreateQueueOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public QueueService() {
            this.Url = global::Xameleon.Properties.Settings.Default.Xameleon_AmazonAWS_SQS_QueueService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event ListQueuesCompletedEventHandler ListQueuesCompleted;
        
        /// <remarks/>
        public event CreateQueueCompletedEventHandler CreateQueueCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("ListQueues", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("ListQueuesResponse", Namespace="http://queue.amazonaws.com/doc/2006-04-01/")]
        public ListQueuesResponse ListQueues([System.Xml.Serialization.XmlElementAttribute("ListQueues", Namespace="http://queue.amazonaws.com/doc/2006-04-01/")] ListQueues ListQueues1) {
            object[] results = this.Invoke("ListQueues", new object[] {
                        ListQueues1});
            return ((ListQueuesResponse)(results[0]));
        }
        
        /// <remarks/>
        public void ListQueuesAsync(ListQueues ListQueues1) {
            this.ListQueuesAsync(ListQueues1, null);
        }
        
        /// <remarks/>
        public void ListQueuesAsync(ListQueues ListQueues1, object userState) {
            if ((this.ListQueuesOperationCompleted == null)) {
                this.ListQueuesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnListQueuesOperationCompleted);
            }
            this.InvokeAsync("ListQueues", new object[] {
                        ListQueues1}, this.ListQueuesOperationCompleted, userState);
        }
        
        private void OnListQueuesOperationCompleted(object arg) {
            if ((this.ListQueuesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ListQueuesCompleted(this, new ListQueuesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("CreateQueue", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("CreateQueueResponse", Namespace="http://queue.amazonaws.com/doc/2006-04-01/")]
        public CreateQueueResponse CreateQueue([System.Xml.Serialization.XmlElementAttribute("CreateQueue", Namespace="http://queue.amazonaws.com/doc/2006-04-01/")] CreateQueue CreateQueue1) {
            object[] results = this.Invoke("CreateQueue", new object[] {
                        CreateQueue1});
            return ((CreateQueueResponse)(results[0]));
        }
        
        /// <remarks/>
        public void CreateQueueAsync(CreateQueue CreateQueue1) {
            this.CreateQueueAsync(CreateQueue1, null);
        }
        
        /// <remarks/>
        public void CreateQueueAsync(CreateQueue CreateQueue1, object userState) {
            if ((this.CreateQueueOperationCompleted == null)) {
                this.CreateQueueOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCreateQueueOperationCompleted);
            }
            this.InvokeAsync("CreateQueue", new object[] {
                        CreateQueue1}, this.CreateQueueOperationCompleted, userState);
        }
        
        private void OnCreateQueueOperationCompleted(object arg) {
            if ((this.CreateQueueCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CreateQueueCompleted(this, new CreateQueueCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="MessageQueue", Namespace="http://queue.amazonaws.com/doc/2006-04-01/")]
    public partial class MessageQueue : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback SendMessageOperationCompleted;
        
        private System.Threading.SendOrPostCallback ReceiveMessageOperationCompleted;
        
        private System.Threading.SendOrPostCallback PeekMessageOperationCompleted;
        
        private System.Threading.SendOrPostCallback DeleteMessageOperationCompleted;
        
        private System.Threading.SendOrPostCallback DeleteQueueOperationCompleted;
        
        private System.Threading.SendOrPostCallback SetVisibilityTimeoutOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetVisibilityTimeoutOperationCompleted;
        
        private System.Threading.SendOrPostCallback AddGrantOperationCompleted;
        
        private System.Threading.SendOrPostCallback RemoveGrantOperationCompleted;
        
        private System.Threading.SendOrPostCallback ListGrantsOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public MessageQueue() {
            this.Url = global::Xameleon.Properties.Settings.Default.Xameleon_AmazonAWS_SQS_QueueService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event SendMessageCompletedEventHandler SendMessageCompleted;
        
        /// <remarks/>
        public event ReceiveMessageCompletedEventHandler ReceiveMessageCompleted;
        
        /// <remarks/>
        public event PeekMessageCompletedEventHandler PeekMessageCompleted;
        
        /// <remarks/>
        public event DeleteMessageCompletedEventHandler DeleteMessageCompleted;
        
        /// <remarks/>
        public event DeleteQueueCompletedEventHandler DeleteQueueCompleted;
        
        /// <remarks/>
        public event SetVisibilityTimeoutCompletedEventHandler SetVisibilityTimeoutCompleted;
        
        /// <remarks/>
        public event GetVisibilityTimeoutCompletedEventHandler GetVisibilityTimeoutCompleted;
        
        /// <remarks/>
        public event AddGrantCompletedEventHandler AddGrantCompleted;
        
        /// <remarks/>
        public event RemoveGrantCompletedEventHandler RemoveGrantCompleted;
        
        /// <remarks/>
        public event ListGrantsCompletedEventHandler ListGrantsCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("SendMessage", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("SendMessageResponse", Namespace="http://queue.amazonaws.com/doc/2006-04-01/")]
        public SendMessageResponse SendMessage([System.Xml.Serialization.XmlElementAttribute("SendMessage", Namespace="http://queue.amazonaws.com/doc/2006-04-01/")] SendMessage SendMessage1) {
            object[] results = this.Invoke("SendMessage", new object[] {
                        SendMessage1});
            return ((SendMessageResponse)(results[0]));
        }
        
        /// <remarks/>
        public void SendMessageAsync(SendMessage SendMessage1) {
            this.SendMessageAsync(SendMessage1, null);
        }
        
        /// <remarks/>
        public void SendMessageAsync(SendMessage SendMessage1, object userState) {
            if ((this.SendMessageOperationCompleted == null)) {
                this.SendMessageOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSendMessageOperationCompleted);
            }
            this.InvokeAsync("SendMessage", new object[] {
                        SendMessage1}, this.SendMessageOperationCompleted, userState);
        }
        
        private void OnSendMessageOperationCompleted(object arg) {
            if ((this.SendMessageCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SendMessageCompleted(this, new SendMessageCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("ReceiveMessage", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("ReceiveMessageResponse", Namespace="http://queue.amazonaws.com/doc/2006-04-01/")]
        public ReceiveMessageResponse ReceiveMessage([System.Xml.Serialization.XmlElementAttribute("ReceiveMessage", Namespace="http://queue.amazonaws.com/doc/2006-04-01/")] ReceiveMessage ReceiveMessage1) {
            object[] results = this.Invoke("ReceiveMessage", new object[] {
                        ReceiveMessage1});
            return ((ReceiveMessageResponse)(results[0]));
        }
        
        /// <remarks/>
        public void ReceiveMessageAsync(ReceiveMessage ReceiveMessage1) {
            this.ReceiveMessageAsync(ReceiveMessage1, null);
        }
        
        /// <remarks/>
        public void ReceiveMessageAsync(ReceiveMessage ReceiveMessage1, object userState) {
            if ((this.ReceiveMessageOperationCompleted == null)) {
                this.ReceiveMessageOperationCompleted = new System.Threading.SendOrPostCallback(this.OnReceiveMessageOperationCompleted);
            }
            this.InvokeAsync("ReceiveMessage", new object[] {
                        ReceiveMessage1}, this.ReceiveMessageOperationCompleted, userState);
        }
        
        private void OnReceiveMessageOperationCompleted(object arg) {
            if ((this.ReceiveMessageCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ReceiveMessageCompleted(this, new ReceiveMessageCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("PeekMessage", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("PeekMessageResponse", Namespace="http://queue.amazonaws.com/doc/2006-04-01/")]
        public PeekMessageResponse PeekMessage([System.Xml.Serialization.XmlElementAttribute("PeekMessage", Namespace="http://queue.amazonaws.com/doc/2006-04-01/")] PeekMessage PeekMessage1) {
            object[] results = this.Invoke("PeekMessage", new object[] {
                        PeekMessage1});
            return ((PeekMessageResponse)(results[0]));
        }
        
        /// <remarks/>
        public void PeekMessageAsync(PeekMessage PeekMessage1) {
            this.PeekMessageAsync(PeekMessage1, null);
        }
        
        /// <remarks/>
        public void PeekMessageAsync(PeekMessage PeekMessage1, object userState) {
            if ((this.PeekMessageOperationCompleted == null)) {
                this.PeekMessageOperationCompleted = new System.Threading.SendOrPostCallback(this.OnPeekMessageOperationCompleted);
            }
            this.InvokeAsync("PeekMessage", new object[] {
                        PeekMessage1}, this.PeekMessageOperationCompleted, userState);
        }
        
        private void OnPeekMessageOperationCompleted(object arg) {
            if ((this.PeekMessageCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.PeekMessageCompleted(this, new PeekMessageCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("DeleteMessage", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("DeleteMessageResponse", Namespace="http://queue.amazonaws.com/doc/2006-04-01/")]
        public DeleteMessageResponse DeleteMessage([System.Xml.Serialization.XmlElementAttribute("DeleteMessage", Namespace="http://queue.amazonaws.com/doc/2006-04-01/")] DeleteMessage DeleteMessage1) {
            object[] results = this.Invoke("DeleteMessage", new object[] {
                        DeleteMessage1});
            return ((DeleteMessageResponse)(results[0]));
        }
        
        /// <remarks/>
        public void DeleteMessageAsync(DeleteMessage DeleteMessage1) {
            this.DeleteMessageAsync(DeleteMessage1, null);
        }
        
        /// <remarks/>
        public void DeleteMessageAsync(DeleteMessage DeleteMessage1, object userState) {
            if ((this.DeleteMessageOperationCompleted == null)) {
                this.DeleteMessageOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDeleteMessageOperationCompleted);
            }
            this.InvokeAsync("DeleteMessage", new object[] {
                        DeleteMessage1}, this.DeleteMessageOperationCompleted, userState);
        }
        
        private void OnDeleteMessageOperationCompleted(object arg) {
            if ((this.DeleteMessageCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DeleteMessageCompleted(this, new DeleteMessageCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("DeleteQueue", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("DeleteQueueResponse", Namespace="http://queue.amazonaws.com/doc/2006-04-01/")]
        public DeleteQueueResponse DeleteQueue([System.Xml.Serialization.XmlElementAttribute("DeleteQueue", Namespace="http://queue.amazonaws.com/doc/2006-04-01/")] DeleteQueue DeleteQueue1) {
            object[] results = this.Invoke("DeleteQueue", new object[] {
                        DeleteQueue1});
            return ((DeleteQueueResponse)(results[0]));
        }
        
        /// <remarks/>
        public void DeleteQueueAsync(DeleteQueue DeleteQueue1) {
            this.DeleteQueueAsync(DeleteQueue1, null);
        }
        
        /// <remarks/>
        public void DeleteQueueAsync(DeleteQueue DeleteQueue1, object userState) {
            if ((this.DeleteQueueOperationCompleted == null)) {
                this.DeleteQueueOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDeleteQueueOperationCompleted);
            }
            this.InvokeAsync("DeleteQueue", new object[] {
                        DeleteQueue1}, this.DeleteQueueOperationCompleted, userState);
        }
        
        private void OnDeleteQueueOperationCompleted(object arg) {
            if ((this.DeleteQueueCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DeleteQueueCompleted(this, new DeleteQueueCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("SetVisibilityTimeout", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("SetVisibilityTimeoutResponse", Namespace="http://queue.amazonaws.com/doc/2006-04-01/")]
        public SetVisibilityTimeoutResponse SetVisibilityTimeout([System.Xml.Serialization.XmlElementAttribute("SetVisibilityTimeout", Namespace="http://queue.amazonaws.com/doc/2006-04-01/")] SetVisibilityTimeout SetVisibilityTimeout1) {
            object[] results = this.Invoke("SetVisibilityTimeout", new object[] {
                        SetVisibilityTimeout1});
            return ((SetVisibilityTimeoutResponse)(results[0]));
        }
        
        /// <remarks/>
        public void SetVisibilityTimeoutAsync(SetVisibilityTimeout SetVisibilityTimeout1) {
            this.SetVisibilityTimeoutAsync(SetVisibilityTimeout1, null);
        }
        
        /// <remarks/>
        public void SetVisibilityTimeoutAsync(SetVisibilityTimeout SetVisibilityTimeout1, object userState) {
            if ((this.SetVisibilityTimeoutOperationCompleted == null)) {
                this.SetVisibilityTimeoutOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSetVisibilityTimeoutOperationCompleted);
            }
            this.InvokeAsync("SetVisibilityTimeout", new object[] {
                        SetVisibilityTimeout1}, this.SetVisibilityTimeoutOperationCompleted, userState);
        }
        
        private void OnSetVisibilityTimeoutOperationCompleted(object arg) {
            if ((this.SetVisibilityTimeoutCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SetVisibilityTimeoutCompleted(this, new SetVisibilityTimeoutCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("GetVisibilityTimeout", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("GetVisibilityTimeoutResponse", Namespace="http://queue.amazonaws.com/doc/2006-04-01/")]
        public GetVisibilityTimeoutResponse GetVisibilityTimeout([System.Xml.Serialization.XmlElementAttribute("GetVisibilityTimeout", Namespace="http://queue.amazonaws.com/doc/2006-04-01/")] GetVisibilityTimeout GetVisibilityTimeout1) {
            object[] results = this.Invoke("GetVisibilityTimeout", new object[] {
                        GetVisibilityTimeout1});
            return ((GetVisibilityTimeoutResponse)(results[0]));
        }
        
        /// <remarks/>
        public void GetVisibilityTimeoutAsync(GetVisibilityTimeout GetVisibilityTimeout1) {
            this.GetVisibilityTimeoutAsync(GetVisibilityTimeout1, null);
        }
        
        /// <remarks/>
        public void GetVisibilityTimeoutAsync(GetVisibilityTimeout GetVisibilityTimeout1, object userState) {
            if ((this.GetVisibilityTimeoutOperationCompleted == null)) {
                this.GetVisibilityTimeoutOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetVisibilityTimeoutOperationCompleted);
            }
            this.InvokeAsync("GetVisibilityTimeout", new object[] {
                        GetVisibilityTimeout1}, this.GetVisibilityTimeoutOperationCompleted, userState);
        }
        
        private void OnGetVisibilityTimeoutOperationCompleted(object arg) {
            if ((this.GetVisibilityTimeoutCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetVisibilityTimeoutCompleted(this, new GetVisibilityTimeoutCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("AddGrant", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("AddGrantResponse", Namespace="http://queue.amazonaws.com/doc/2006-04-01/")]
        public AddGrantResponse AddGrant([System.Xml.Serialization.XmlElementAttribute("AddGrant", Namespace="http://queue.amazonaws.com/doc/2006-04-01/")] AddGrantRequest AddGrant1) {
            object[] results = this.Invoke("AddGrant", new object[] {
                        AddGrant1});
            return ((AddGrantResponse)(results[0]));
        }
        
        /// <remarks/>
        public void AddGrantAsync(AddGrantRequest AddGrant1) {
            this.AddGrantAsync(AddGrant1, null);
        }
        
        /// <remarks/>
        public void AddGrantAsync(AddGrantRequest AddGrant1, object userState) {
            if ((this.AddGrantOperationCompleted == null)) {
                this.AddGrantOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAddGrantOperationCompleted);
            }
            this.InvokeAsync("AddGrant", new object[] {
                        AddGrant1}, this.AddGrantOperationCompleted, userState);
        }
        
        private void OnAddGrantOperationCompleted(object arg) {
            if ((this.AddGrantCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AddGrantCompleted(this, new AddGrantCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("RemoveGrant", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("RemoveGrantResponse", Namespace="http://queue.amazonaws.com/doc/2006-04-01/")]
        public RemoveGrantResponse RemoveGrant([System.Xml.Serialization.XmlElementAttribute("RemoveGrant", Namespace="http://queue.amazonaws.com/doc/2006-04-01/")] RemoveGrantRequest RemoveGrant1) {
            object[] results = this.Invoke("RemoveGrant", new object[] {
                        RemoveGrant1});
            return ((RemoveGrantResponse)(results[0]));
        }
        
        /// <remarks/>
        public void RemoveGrantAsync(RemoveGrantRequest RemoveGrant1) {
            this.RemoveGrantAsync(RemoveGrant1, null);
        }
        
        /// <remarks/>
        public void RemoveGrantAsync(RemoveGrantRequest RemoveGrant1, object userState) {
            if ((this.RemoveGrantOperationCompleted == null)) {
                this.RemoveGrantOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRemoveGrantOperationCompleted);
            }
            this.InvokeAsync("RemoveGrant", new object[] {
                        RemoveGrant1}, this.RemoveGrantOperationCompleted, userState);
        }
        
        private void OnRemoveGrantOperationCompleted(object arg) {
            if ((this.RemoveGrantCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.RemoveGrantCompleted(this, new RemoveGrantCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("ListGrants", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("ListGrantsResponse", Namespace="http://queue.amazonaws.com/doc/2006-04-01/")]
        public ListGrantsResponse ListGrants([System.Xml.Serialization.XmlElementAttribute("ListGrants", Namespace="http://queue.amazonaws.com/doc/2006-04-01/")] ListGrantsRequest ListGrants1) {
            object[] results = this.Invoke("ListGrants", new object[] {
                        ListGrants1});
            return ((ListGrantsResponse)(results[0]));
        }
        
        /// <remarks/>
        public void ListGrantsAsync(ListGrantsRequest ListGrants1) {
            this.ListGrantsAsync(ListGrants1, null);
        }
        
        /// <remarks/>
        public void ListGrantsAsync(ListGrantsRequest ListGrants1, object userState) {
            if ((this.ListGrantsOperationCompleted == null)) {
                this.ListGrantsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnListGrantsOperationCompleted);
            }
            this.InvokeAsync("ListGrants", new object[] {
                        ListGrants1}, this.ListGrantsOperationCompleted, userState);
        }
        
        private void OnListGrantsOperationCompleted(object arg) {
            if ((this.ListGrantsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ListGrantsCompleted(this, new ListGrantsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class ListQueues {
        
        private string queueNamePrefixField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="NCName")]
        public string QueueNamePrefix {
            get {
                return this.queueNamePrefixField;
            }
            set {
                this.queueNamePrefixField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://access.amazonaws.com/doc/2006-01-01/")]
    public partial class Grant {
        
        private Grantee granteeField;
        
        private string permissionField;
        
        /// <remarks/>
        public Grantee Grantee {
            get {
                return this.granteeField;
            }
            set {
                this.granteeField = value;
            }
        }
        
        /// <remarks/>
        public string Permission {
            get {
                return this.permissionField;
            }
            set {
                this.permissionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Group))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(User))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(CanonicalUser))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(AmazonCredential))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(AmazonCustomerByEmail))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://access.amazonaws.com/doc/2006-01-01/")]
    public abstract partial class Grantee {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://access.amazonaws.com/doc/2006-01-01/")]
    public partial class Group : Grantee {
        
        private string uRIField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="anyURI")]
        public string URI {
            get {
                return this.uRIField;
            }
            set {
                this.uRIField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(CanonicalUser))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(AmazonCredential))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(AmazonCustomerByEmail))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://access.amazonaws.com/doc/2006-01-01/")]
    public abstract partial class User : Grantee {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://access.amazonaws.com/doc/2006-01-01/")]
    public partial class CanonicalUser : User {
        
        private string idField;
        
        private string displayNameField;
        
        /// <remarks/>
        public string ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string DisplayName {
            get {
                return this.displayNameField;
            }
            set {
                this.displayNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://access.amazonaws.com/doc/2006-01-01/")]
    public partial class AmazonCredential : User {
        
        private string credentialField;
        
        /// <remarks/>
        public string Credential {
            get {
                return this.credentialField;
            }
            set {
                this.credentialField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://access.amazonaws.com/doc/2006-01-01/")]
    public partial class AmazonCustomerByEmail : User {
        
        private string emailAddressField;
        
        /// <remarks/>
        public string EmailAddress {
            get {
                return this.emailAddressField;
            }
            set {
                this.emailAddressField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://access.amazonaws.com/doc/2006-01-01/")]
    public partial class ListGrantsResponse {
        
        private Grant[] grantListField;
        
        private ResponseStatus1 responseStatusField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("GrantList")]
        public Grant[] GrantList {
            get {
                return this.grantListField;
            }
            set {
                this.grantListField = value;
            }
        }
        
        /// <remarks/>
        public ResponseStatus1 ResponseStatus {
            get {
                return this.responseStatusField;
            }
            set {
                this.responseStatusField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="ResponseStatus", Namespace="http://access.amazonaws.com/doc/2006-01-01/")]
    public partial class ResponseStatus1 {
        
        private string statusCodeField;
        
        private string statusMessageField;
        
        /// <remarks/>
        public string StatusCode {
            get {
                return this.statusCodeField;
            }
            set {
                this.statusCodeField = value;
            }
        }
        
        /// <remarks/>
        public string StatusMessage {
            get {
                return this.statusMessageField;
            }
            set {
                this.statusMessageField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://access.amazonaws.com/doc/2006-01-01/")]
    public partial class ListGrantsRequest {
        
        private Grantee granteeField;
        
        private string permissionField;
        
        /// <remarks/>
        public Grantee Grantee {
            get {
                return this.granteeField;
            }
            set {
                this.granteeField = value;
            }
        }
        
        /// <remarks/>
        public string Permission {
            get {
                return this.permissionField;
            }
            set {
                this.permissionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://access.amazonaws.com/doc/2006-01-01/")]
    public partial class RemoveGrantResponse {
        
        private ResponseStatus1 responseStatusField;
        
        /// <remarks/>
        public ResponseStatus1 ResponseStatus {
            get {
                return this.responseStatusField;
            }
            set {
                this.responseStatusField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://access.amazonaws.com/doc/2006-01-01/")]
    public partial class RemoveGrantRequest {
        
        private Grantee granteeField;
        
        private string permissionField;
        
        /// <remarks/>
        public Grantee Grantee {
            get {
                return this.granteeField;
            }
            set {
                this.granteeField = value;
            }
        }
        
        /// <remarks/>
        public string Permission {
            get {
                return this.permissionField;
            }
            set {
                this.permissionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://access.amazonaws.com/doc/2006-01-01/")]
    public partial class AddGrantResponse {
        
        private ResponseStatus1 responseStatusField;
        
        /// <remarks/>
        public ResponseStatus1 ResponseStatus {
            get {
                return this.responseStatusField;
            }
            set {
                this.responseStatusField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://access.amazonaws.com/doc/2006-01-01/")]
    public partial class AddGrantRequest {
        
        private Grantee granteeField;
        
        private string permissionField;
        
        /// <remarks/>
        public Grantee Grantee {
            get {
                return this.granteeField;
            }
            set {
                this.granteeField = value;
            }
        }
        
        /// <remarks/>
        public string Permission {
            get {
                return this.permissionField;
            }
            set {
                this.permissionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class ListQueuesResponse {
        
        private string[] queueUrlField;
        
        private ResponseStatus responseStatusField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("QueueUrl", DataType="anyURI")]
        public string[] QueueUrl {
            get {
                return this.queueUrlField;
            }
            set {
                this.queueUrlField = value;
            }
        }
        
        /// <remarks/>
        public ResponseStatus ResponseStatus {
            get {
                return this.responseStatusField;
            }
            set {
                this.responseStatusField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class ResponseStatus {
        
        private string statusCodeField;
        
        private string messageField;
        
        private string requestIdField;
        
        /// <remarks/>
        public string StatusCode {
            get {
                return this.statusCodeField;
            }
            set {
                this.statusCodeField = value;
            }
        }
        
        /// <remarks/>
        public string Message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
            }
        }
        
        /// <remarks/>
        public string RequestId {
            get {
                return this.requestIdField;
            }
            set {
                this.requestIdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class CreateQueue {
        
        private string queueNameField;
        
        private string defaultVisibilityTimeoutField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="NCName")]
        public string QueueName {
            get {
                return this.queueNameField;
            }
            set {
                this.queueNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string DefaultVisibilityTimeout {
            get {
                return this.defaultVisibilityTimeoutField;
            }
            set {
                this.defaultVisibilityTimeoutField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class CreateQueueResponse {
        
        private string queueUrlField;
        
        private ResponseStatus responseStatusField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="anyURI")]
        public string QueueUrl {
            get {
                return this.queueUrlField;
            }
            set {
                this.queueUrlField = value;
            }
        }
        
        /// <remarks/>
        public ResponseStatus ResponseStatus {
            get {
                return this.responseStatusField;
            }
            set {
                this.responseStatusField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class SendMessage {
        
        private string messageBodyField;
        
        /// <remarks/>
        public string MessageBody {
            get {
                return this.messageBodyField;
            }
            set {
                this.messageBodyField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class SendMessageResponse {
        
        private string messageIdField;
        
        private ResponseStatus responseStatusField;
        
        /// <remarks/>
        public string MessageId {
            get {
                return this.messageIdField;
            }
            set {
                this.messageIdField = value;
            }
        }
        
        /// <remarks/>
        public ResponseStatus ResponseStatus {
            get {
                return this.responseStatusField;
            }
            set {
                this.responseStatusField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class ReceiveMessage {
        
        private string numberOfMessagesField;
        
        private string visibilityTimeoutField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string NumberOfMessages {
            get {
                return this.numberOfMessagesField;
            }
            set {
                this.numberOfMessagesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string VisibilityTimeout {
            get {
                return this.visibilityTimeoutField;
            }
            set {
                this.visibilityTimeoutField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class ReceiveMessageResponse {
        
        private Message[] messageField;
        
        private ResponseStatus responseStatusField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Message")]
        public Message[] Message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
            }
        }
        
        /// <remarks/>
        public ResponseStatus ResponseStatus {
            get {
                return this.responseStatusField;
            }
            set {
                this.responseStatusField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class Message {
        
        private string messageIdField;
        
        private string messageBodyField;
        
        /// <remarks/>
        public string MessageId {
            get {
                return this.messageIdField;
            }
            set {
                this.messageIdField = value;
            }
        }
        
        /// <remarks/>
        public string MessageBody {
            get {
                return this.messageBodyField;
            }
            set {
                this.messageBodyField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class PeekMessage {
        
        private string messageIdField;
        
        /// <remarks/>
        public string MessageId {
            get {
                return this.messageIdField;
            }
            set {
                this.messageIdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class PeekMessageResponse {
        
        private Message messageField;
        
        private ResponseStatus responseStatusField;
        
        /// <remarks/>
        public Message Message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
            }
        }
        
        /// <remarks/>
        public ResponseStatus ResponseStatus {
            get {
                return this.responseStatusField;
            }
            set {
                this.responseStatusField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class DeleteMessage {
        
        private string messageIdField;
        
        /// <remarks/>
        public string MessageId {
            get {
                return this.messageIdField;
            }
            set {
                this.messageIdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class DeleteMessageResponse {
        
        private ResponseStatus responseStatusField;
        
        /// <remarks/>
        public ResponseStatus ResponseStatus {
            get {
                return this.responseStatusField;
            }
            set {
                this.responseStatusField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class DeleteQueue {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class DeleteQueueResponse {
        
        private ResponseStatus responseStatusField;
        
        /// <remarks/>
        public ResponseStatus ResponseStatus {
            get {
                return this.responseStatusField;
            }
            set {
                this.responseStatusField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class SetVisibilityTimeout {
        
        private string visibilityTimeoutField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string VisibilityTimeout {
            get {
                return this.visibilityTimeoutField;
            }
            set {
                this.visibilityTimeoutField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class SetVisibilityTimeoutResponse {
        
        private ResponseStatus responseStatusField;
        
        /// <remarks/>
        public ResponseStatus ResponseStatus {
            get {
                return this.responseStatusField;
            }
            set {
                this.responseStatusField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class GetVisibilityTimeout {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class GetVisibilityTimeoutResponse {
        
        private string visibilityTimeoutField;
        
        private ResponseStatus responseStatusField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string VisibilityTimeout {
            get {
                return this.visibilityTimeoutField;
            }
            set {
                this.visibilityTimeoutField = value;
            }
        }
        
        /// <remarks/>
        public ResponseStatus ResponseStatus {
            get {
                return this.responseStatusField;
            }
            set {
                this.responseStatusField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    public delegate void ListQueuesCompletedEventHandler(object sender, ListQueuesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ListQueuesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ListQueuesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ListQueuesResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ListQueuesResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    public delegate void CreateQueueCompletedEventHandler(object sender, CreateQueueCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CreateQueueCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CreateQueueCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public CreateQueueResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((CreateQueueResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    public delegate void SendMessageCompletedEventHandler(object sender, SendMessageCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SendMessageCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SendMessageCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public SendMessageResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((SendMessageResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    public delegate void ReceiveMessageCompletedEventHandler(object sender, ReceiveMessageCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ReceiveMessageCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ReceiveMessageCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ReceiveMessageResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ReceiveMessageResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    public delegate void PeekMessageCompletedEventHandler(object sender, PeekMessageCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class PeekMessageCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal PeekMessageCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public PeekMessageResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((PeekMessageResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    public delegate void DeleteMessageCompletedEventHandler(object sender, DeleteMessageCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DeleteMessageCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal DeleteMessageCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public DeleteMessageResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((DeleteMessageResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    public delegate void DeleteQueueCompletedEventHandler(object sender, DeleteQueueCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DeleteQueueCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal DeleteQueueCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public DeleteQueueResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((DeleteQueueResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    public delegate void SetVisibilityTimeoutCompletedEventHandler(object sender, SetVisibilityTimeoutCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SetVisibilityTimeoutCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SetVisibilityTimeoutCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public SetVisibilityTimeoutResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((SetVisibilityTimeoutResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    public delegate void GetVisibilityTimeoutCompletedEventHandler(object sender, GetVisibilityTimeoutCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetVisibilityTimeoutCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetVisibilityTimeoutCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public GetVisibilityTimeoutResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((GetVisibilityTimeoutResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    public delegate void AddGrantCompletedEventHandler(object sender, AddGrantCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AddGrantCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AddGrantCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public AddGrantResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((AddGrantResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    public delegate void RemoveGrantCompletedEventHandler(object sender, RemoveGrantCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class RemoveGrantCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal RemoveGrantCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public RemoveGrantResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((RemoveGrantResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    public delegate void ListGrantsCompletedEventHandler(object sender, ListGrantsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ListGrantsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ListGrantsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ListGrantsResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ListGrantsResponse)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591